package com.socratessimulator.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * AAW = AAW, AB = AB, ABW = ABW, AKW = AKW, ANW = ANW, AOW = AOW, AOW-OBR = AOWOBR, AOWOR = AOWOR, AWBZ = AWBZ, AWW = AWW, BB = BB, BBZ = BBZ, BBZB = BBZB, BBZBB = BBZBB, BBZL = BBZL, CSV = CSV, INTW = INTW, IOAW = IOAW, IOAZ = IOAZ, IOW = IOW, IVA = IVA, KB = KB, KOP = KOP, NWJ = NWJ, OSV = OSV, PVW = PVW, PWJ = PWJ, REA = REA, RW = RW, RWW = RWW, TRI = TRI, TW = TW, VUT = VUT, WAJ = WAJ, WAMIL = WAMIL, WAO = WAO, WAZ = WAZ, WAZO = WAZO, WBIA = WBIA, WGA = WGA, WHK = WHK, WIA = WIA, WIJ = WIJ, WMO = WMO, WSW = WSW, WVG = WVG, WW = WW, WWAJ = WWAJ, WWB = WWB, WWF = WWF, WWIK = WWIK, ZFW = ZFW, ZVW = ZVW, ZW = ZW
 * Values: AAW,AB,ABW,AKW,ANW,AOW,AOWMinusOBR,AOWOR,AWBZ,AWW,BB,BBZ,BBZB,BBZBB,BBZL,CSV,INTW,IOAW,IOAZ,IOW,IVA,KB,KOP,NWJ,OSV,PVW,PWJ,REA,RW,RWW,TRI,TW,VUT,WAJ,WAMIL,WAO,WAZ,WAZO,WBIA,WGA,WHK,WIA,WIJ,WMO,WSW,WVG,WW,WWAJ,WWB,WWF,WWIK,ZFW,ZVW,ZW
 */
enum class UitkeringInkomstensoortUitkering(val value: String) {

    @JsonProperty("AAW")
    AAW("AAW"),
    @JsonProperty("AB")
    AB("AB"),
    @JsonProperty("ABW")
    ABW("ABW"),
    @JsonProperty("AKW")
    AKW("AKW"),
    @JsonProperty("ANW")
    ANW("ANW"),
    @JsonProperty("AOW")
    AOW("AOW"),
    @JsonProperty("AOW-OBR")
    AOWMinusOBR("AOW-OBR"),
    @JsonProperty("AOWOR")
    AOWOR("AOWOR"),
    @JsonProperty("AWBZ")
    AWBZ("AWBZ"),
    @JsonProperty("AWW")
    AWW("AWW"),
    @JsonProperty("BB")
    BB("BB"),
    @JsonProperty("BBZ")
    BBZ("BBZ"),
    @JsonProperty("BBZB")
    BBZB("BBZB"),
    @JsonProperty("BBZBB")
    BBZBB("BBZBB"),
    @JsonProperty("BBZL")
    BBZL("BBZL"),
    @JsonProperty("CSV")
    CSV("CSV"),
    @JsonProperty("INTW")
    INTW("INTW"),
    @JsonProperty("IOAW")
    IOAW("IOAW"),
    @JsonProperty("IOAZ")
    IOAZ("IOAZ"),
    @JsonProperty("IOW")
    IOW("IOW"),
    @JsonProperty("IVA")
    IVA("IVA"),
    @JsonProperty("KB")
    KB("KB"),
    @JsonProperty("KOP")
    KOP("KOP"),
    @JsonProperty("NWJ")
    NWJ("NWJ"),
    @JsonProperty("OSV")
    OSV("OSV"),
    @JsonProperty("PVW")
    PVW("PVW"),
    @JsonProperty("PWJ")
    PWJ("PWJ"),
    @JsonProperty("REA")
    REA("REA"),
    @JsonProperty("RW")
    RW("RW"),
    @JsonProperty("RWW")
    RWW("RWW"),
    @JsonProperty("TRI")
    TRI("TRI"),
    @JsonProperty("TW")
    TW("TW"),
    @JsonProperty("VUT")
    VUT("VUT"),
    @JsonProperty("WAJ")
    WAJ("WAJ"),
    @JsonProperty("WAMIL")
    WAMIL("WAMIL"),
    @JsonProperty("WAO")
    WAO("WAO"),
    @JsonProperty("WAZ")
    WAZ("WAZ"),
    @JsonProperty("WAZO")
    WAZO("WAZO"),
    @JsonProperty("WBIA")
    WBIA("WBIA"),
    @JsonProperty("WGA")
    WGA("WGA"),
    @JsonProperty("WHK")
    WHK("WHK"),
    @JsonProperty("WIA")
    WIA("WIA"),
    @JsonProperty("WIJ")
    WIJ("WIJ"),
    @JsonProperty("WMO")
    WMO("WMO"),
    @JsonProperty("WSW")
    WSW("WSW"),
    @JsonProperty("WVG")
    WVG("WVG"),
    @JsonProperty("WW")
    WW("WW"),
    @JsonProperty("WWAJ")
    WWAJ("WWAJ"),
    @JsonProperty("WWB")
    WWB("WWB"),
    @JsonProperty("WWF")
    WWF("WWF"),
    @JsonProperty("WWIK")
    WWIK("WWIK"),
    @JsonProperty("ZFW")
    ZFW("ZFW"),
    @JsonProperty("ZVW")
    ZVW("ZVW"),
    @JsonProperty("ZW")
    ZW("ZW")
}

